name: GKI Build SuKiSu SUSFS
on:
  workflow_dispatch:
    inputs:
      ci_VERSION:
        description: "谷歌ci版本"
        required: true
        default: ''
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android14'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.1'
      KERNEL_NAME:
        type: string
        description: "自定义内核后缀 (留空则使用随机字符串)"
        required: false
        default: ""
      BUILD_TIME:
        type: string
        description: "自定义构建时间 (输入F使用当前时间)"
        required: false
        default: "Sun Jun 15 14:56:02 UTC 2025"
      sukisu_tag:
        description: "自定义版本来源后缀"
        required: false
        default: "闲鱼-搞机英雄-禁止黑灰违法犯罪倒卖"
      enable_patch:
       description: "是否启用6.6.30补丁"
       required: false
       default: false
       type: boolean
      enable_oneplus:
       description: "是否启用一加开机补丁"
       required: false
       default: false
       type: boolean
      sukisu_version:
        description: "sukisu分支"
        required: true
        default: "susfs-main"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Configure Git
        run: |
         git config --global user.name "build"
         git config --global user.email "3028172686@qq.com"

      - name: Install dependencies
        run: |
         sudo apt update && sudo apt upgrade -y
         sudo apt install -y curl ccache git python3 repo libelf-dev
        
      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo'
         repo init --depth=1 --u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/kernel/manifest -b common-${{ github.event.inputs.ci_VERSION }} --repo-rev=v2.16
         REMOTE_BRANCH=$(git ls-remote https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/kernel/common ${{ github.event.inputs.ci_VERSION }})
         DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
         if grep -q deprecated <<< $REMOTE_BRANCH; then
         echo "Found deprecated branch: ${{ github.event.inputs.ci_VERSION }}"
         sed -i 's/"'${{ github.event.inputs.ci_VERSION }}'"/"deprecated\/'${{ github.event.inputs.ci_VERSION }}'"/g' $DEFAULT_MANIFEST_PATH
         cat $DEFAULT_MANIFEST_PATH
         fi
         repo --version
         repo --trace sync -c -j$(nproc --all) --no-tags

         rm common/android/abi_gki_protected_exports_* || echo "No protected exports!"
         
      - name: Set up SukiSU
        run: |
         cd kernel_workspace
         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s ${{ github.event.inputs.sukisu_version }}
         cd KernelSU
         TAG_SUFFIX="${{ github.event.inputs.sukisu_tag }}"
         # 使用正确变量名 KSU_VERSION_API 替换函数体
         sed -i 's|\$(shell cd \$(srctree)/\$(src); \$(GIT_BIN) rev-parse --abbrev-ref HEAD)|\$TAG_SUFFIX|g' kernel/Makefile
         echo "✅ Injected custom version: v$(KSU_VERSION)@$TAG_SUFFIX"
         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10700)
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
         export KSU_VERSION=$KSU_VERSION
         
      - name: Set up susfs
        run: |
           cd kernel_workspace
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
           
           git clone https://github.com/ShirkNeko/SukiSU_patch.git
           cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
           cp susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

           # Apply patches
           cd ./common
           if ${{inputs.enable_patch }}; then
           sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
           sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
           fi
           patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
           # cp ../kernel_patches/69_hide_stuff.patch ./
           cp ../SukiSU_patch/hooks/scope_min_manual_hooks_v1.5.patch ./
           # patch -p1 -F 3 < 69_hide_stuff.patch
           patch -p1 -F 3 < scope_min_manual_hooks_v1.5.patch        
      
      # Custom kernel build time, without adding #1 SMP PREEMPT 自定义内核构建时间，不要加入#1 SMP PREEMPT
      - name: Custom BUILD_TIME
        shell: bash
        run: |
          INPUT_TIME="${{ github.event.inputs.BUILD_TIME }}"
          if [[ -n "$INPUT_TIME" && "$INPUT_TIME" != *[Ff]* ]]; then
            DATESTR="$INPUT_TIME"
            echo "Using input BUILD_TIME: $DATESTR"
          else
            DATESTR="$(TZ='UTC' date +'%a %b %d %T %Z %Y')"
            echo "Using UTC time as fallback: $DATESTR"
          fi
          echo "KBUILD_BUILD_TIMESTAMP=${DATESTR}" >> "$GITHUB_ENV"
          echo "KBUILD_BUILD_VERSION=1" >> "$GITHUB_ENV"
          cd kernel_workspace/
          for f in common/scripts/mkcompile_h; do
            if [ -f "$f" ]; then
              echo "Patching mkcompile_h with BUILD_TIME=$DATESTR"
              if grep -q 'UTS_VERSION=' "$f"; then
                perl -pi -e "s{UTS_VERSION=\"\\\$\\(.*?\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $DATESTR\"}" "$f"
              else
                perl -0777 -pi -e "s{cat <<EOF}{cat <<EOF\n#undef UTS_VERSION\n#define UTS_VERSION \"#1 SMP PREEMPT $DATESTR\" } unless /UTS_VERSION/" "$f"
              fi
            fi
          done
          
      - name: oneplus
        if: ${{inputs.enable_oneplus }}
        run: |
         cd kernel_workspace
         git clone https://$TOKEN@github.com/JiuGeFaCai/sturdy-journey.git
         cp ./sturdy-journey/fix.patch ./common/
         cd ./common
         patch -p1 -F 3 < fix.patch

      - name: Kernel Version Handling
        run: |
          cd kernel_workspace
          # 获取内核 Android 版本号(KANDROID_VERSION)以及内核版本号(KERNEL_VERSION)
          for f in ./common/build.config.constants ./common/build.config.common; do
            if [ -f "$f" ]; then
              BRANCH=$(grep -m1 '^BRANCH=' "$f" | cut -d= -f2)
              [ -n "$BRANCH" ] && break
            fi
          done

          if [ -n "$BRANCH" ]; then
            echo "KANDROID_VERSION=${BRANCH%-*}" >> $GITHUB_ENV
            echo "KERNEL_VERSION=${BRANCH#*-}" >> $GITHUB_ENV
          else
            echo "No BRANCH found in build.config files"
          fi

          # 从 Makefile 获取完整内核版本号(TKERNEL_VERSION)以及可选的修改内核等级
          ORIG_VERSION=$(awk '/^VERSION =/ {v=$3} /^PATCHLEVEL =/ {p=$3} /^SUBLEVEL =/ {s=$3} END {print v"."p"."s}' ./common/Makefile)

          # 强制修改 SUBLEVEL(内核等级)，默认关闭
          # sed -i 's/^SUBLEVEL[[:space:]]*=[[:space:]]*.*/SUBLEVEL = 99/' ./common/Makefile

          # 读取修改后的版本
          NEW_VERSION=$(awk '/^VERSION =/ {v=$3} /^PATCHLEVEL =/ {p=$3} /^SUBLEVEL =/ {s=$3} END {print v"."p"."s}' ./common/Makefile)

          if [ "$ORIG_VERSION" != "$NEW_VERSION" ]; then
            echo "Kernel Version:$ORIG_VERSION->$NEW_VERSION"
            echo "TKERNEL_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          else
            echo "Kernel Version:$ORIG_VERSION No changes"
            echo "TKERNEL_VERSION=$ORIG_VERSION" >> $GITHUB_ENV
          fi
         
      - name: Add SUSFS Configuration Settings
        run: |
          cd kernel_workspace
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig

          # Add VFS configuration settings
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
         
          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          cd common
          if [ -f "BUILD.bazel" ]; then
          sed -i '/"protected_exports_list": "android\/abi_gki_protected_exports_aarch64"/d' BUILD.bazel
          fi
          git add -A && git commit -a -m "BUILD Kernel"

      - name: Add make name
        if: ${{ github.event.inputs.KERNEL_NAME != '' }}
        run: |
         cd kernel_workspace
         if [ "${{ github.event.inputs.KERNEL_VERSION }}" != "6.6" ]; then
         sed -i '$s|echo "\$res"|echo "\${{ github.event.inputs.KERNEL_NAME }}"|' ./common/scripts/setlocalversion
         else
         sed -i '$s|${file_localversion}|${{ github.event.inputs.KERNEL_NAME }}|' ./common/scripts/setlocalversion
         fi
   
      - name: Build kernel
        run: |
         cd kernel_workspace
         if [ -e build/build.sh ]; then
           LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
         else
           tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist
         fi

      - name: Make AnyKernel3
        run: |
         OUTDIR=kernel_workspace/out/${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}/dist
         if [ ! -e $OUTDIR ]; then
           OUTDIR=kernel_workspace/dist
         fi
         mkdir output
         cp $OUTDIR/Image ./output/
         cd output
         curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux" -o patch_linux
         chmod +x patch_linux
         ./patch_linux
         rm -f Image
         mv oImage Image
         cd ..
         git clone https://github.com/WildPlusKernel/AnyKernel3.git --depth=1
         rm -rf ./AnyKernel3/.git
         cp ./output/Image ./AnyKernel3/

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: SuKiSu_${{ env.KSUVER }}_${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}-(${{ env.TKERNEL_VERSION }})
         path: ./AnyKernel3/*
         
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
         name: Image
         path: ./output/*
